### ISSUE TITLE
I'd like to ask why you chose to use bindgen but not cxx.

### ISSUE THREAD

**Issue by ghjdegithub** [thewh1teagle/sherpa-rs#36]

**Comment by thewh1teagle** [comment]
cxx is used for C++, and bindgen is for C. Since sherpa-onnx exposes a C API, we use bindgen. Even if it were C++, I wouldn't choose cxx. I worked with a cxx codebase a while ago, and I find that using bindgen along with custom C++ wrappers makes the code much more readable when writing bindings for a C++ library.

**Comment by thewh1teagle** [comment]
For instance see this cxx crate which in my opinion is not readable at all:
https://github.com/jkawamoto/ctranslate2-rs/tree/main/src/sys

Versus another small wrapper I created to C++ code:
https://github.com/thewh1teagle/knf-rs/tree/main/sys (See knfc folder)

**Comment by ghjdegithub** [comment]
> FYI: [k2-fsa/sherpa-onnx#1455](https://github.com/k2-fsa/sherpa-onnx/pull/1455) provides a C++ wrapper for sherpa-onnx's C API.

What are the languages currently officially supported by the API, can you list them on the reademe?

**Comment by csukuangfj** [comment]
Please see
https://github.com/k2-fsa/sherpa-onnx?tab=readme-ov-file#supported-programming-languages

12 languages are supported by sherpa-onnx at present.

We may support more if needed.

<img width="778" alt="Screenshot 2024-10-23 at 19 38 12" src="https://github.com/user-attachments/assets/2b498b10-2f85-407b-af2d-264c4917306d">

**Comment by ghjdegithub** [comment]
> officially

I mean to distinguish between official support and unofficial support
