### ISSUE TITLE
is it possible to use this with pyannote_rs (error: linking with `link.exe` failed: exit code: 1319)

### ISSUE THREAD

**Issue by altunenes** [thewh1teagle/sherpa-rs#9]
I get a link error even when I just load the models without doing anything, like below. Is there any way to solve this?
What I want is to be able to use the segmentation and id processes with pyannote_rs and  for the transciption sherpa-rs. Because pyannote_rs almost give 100% accuracy in terms of segmentation and speaker identification. and I felt that sherpa-rs gave better results in transcripts on my tests.

```rust
use eyre::{bail, Result};
use sherpa_rs::{
    embedding_manager, speaker_id,
    transcribe::whisper::WhisperRecognizer,
    vad::{Vad, VadConfig},
};
use rubato::{Resampler, SincFixedIn, SincInterpolationParameters, SincInterpolationType, WindowFunction};
use pyannote_rs::{EmbeddingExtractor, EmbeddingManager};

fn main() -> Result<()> {
    // Configuration
    let max_speakers = 6;
    let search_threshold = 0.5;
    let embedding_model_path = "wespeaker_en_voxceleb_CAM++.onnx";
    let segmentation_model_path = "segmentation-3.0.onnx";
    // Initialize pyannote-rs components
    let mut embedding_extractor = EmbeddingExtractor::new(embedding_model_path)?;
    let mut embedding_manager = EmbeddingManager::new(max_speakers);
    // Initialize Whisper recognizer
    let mut recognizer = WhisperRecognizer::new(
        "tiny-decoder.onnx".into(),
        "tiny-encoder.onnx".into(),
        "tiny-tokens.txt".into(),
        "sv".into(),
        Some(true),
        Some("coreml".to_string()),
        None,
        None,
    );
    Ok(())
}
```

full log:
[log.txt](https://github.com/user-attachments/files/16553468/log.txt)

**Comment by thewh1teagle** [comment]
It's good idea to try use whisper with sherpa-rs. I'm curious what will be the speed with medium / tiny model compared to whisper.cpp (with vibe).

The important line from the log is this:

```console
libsherpa_rs_sys.rlib(c-api.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in libknf_rs_sys.rlib(knfc.obj)
```

It's issues with linking MSVC.
For some reason sherpa-s linking MSVC debug mode and knf-rs linking MSVC in release mode.
I'm not sure why. I build both with the same profiles. 

https://github.com/thewh1teagle/sherpa-rs/blob/main/sys/build.rs#L154
https://github.com/thewh1teagle/knf-rs/blob/main/sys/build.rs#L43

Both options passed to Cmake.
Also in both I link MSVC statically with `static_crt(true)` which passed to Cmake as well.

I suspect that the issue comes from the Cmake of knfc - C wrapper here
https://github.com/thewh1teagle/knf-rs/blob/main/sys/knfc/CMakeLists.txt

**Comment by altunenes** [comment]
To be honest, "tiny-decoder/encoder.onnx" works really very well, especially with different languages like Swedish.  

When I used the small model of whishper.cpp to increase the accuracy, I was surprised to see that I could only reached the same accuracy level of tiny.onnx in sherpa-rs.

**Comment by altunenes** [comment]
can explicitly set the MSVC runtime library in both build.rs files fix the issue? (inspired by a comment on bellow)

https://forum.juce.com/t/how-to-enable-msvc-static-runtime-linking-with-cmake/40917/5

```
if cfg!(windows) {
    config.define("CMAKE_MSVC_RUNTIME_LIBRARY", "MultiThreaded$<$<CONFIG:Debug>:Debug>");
}
```
https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html

**Comment by thewh1teagle** [comment]
I think that `kaldi-native-fbank` doesn't respect `-DCMAKE_BUILD_TYPE=Debug` so it links msvc static but sherpa does respect it.

@csukuangfj
Can you help with that?

**Comment by csukuangfj** [comment]
Please add the following lines
https://github.com/k2-fsa/sherpa-onnx/blob/94e256244d3ed15123f1ab159839c5ae62454d3d/CMakeLists.txt#L113
to kaldi-native-fbank's CMakeLists.txt

**Comment by thewh1teagle** [comment]
@altunenes 
Fixed and updated sherpa-rs repository.

*Few notes*
1. `sherpa-onnx` has some bug with medium models lead to crash. only tiny works.
2. tiny model is 2x times faster than `whisper.cpp` on CPU in non batch mode! (iterate and decode less than 30s)
3. `sherpa-onnx` has onnxruntime that conflict with `pyannote-rs`. sherpa-onnx link it statically by default and I enabled by default feature flag in pyannote-rs example to load it dynamic. DLLs need to be in the PATH of executable.
It won't work with DirectML feature flag since it's enable shared load for sherpa-onnx.

**Comment by altunenes** [comment]
sorry for the delay, I will test it right now. 

By the way you probably forgot the publish  0.1.9 in creates.io :-)

**Comment by altunenes** [comment]
it just runs. I didn't do anything special by the way.  🥇  Thank you!!!

I tested this:
https://github.com/thewh1teagle/sherpa-rs/blob/main/examples/pyannote.rs
my cargo.toml:
```
sherpa-rs = { git = "https://github.com/thewh1teagle/sherpa-rs" }
knf-rs = "0.1.4"
pyannote-rs = { version = "0.2.3", features = ["load-dynamic"] }
```
